stages:
  - build

flutter_build_android:
  stage: build # kind of jo
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter #h
