stages:
  - build

flutter_build_android:
  stage: build # kind of job
  services:
    - docker:dind
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

